export const SCREENS = {
  HOME: 'Home',
  EXPLORE: 'Explore',
  APPOINTMENTS: 'Appointments',
  PROFILE: 'Profile',
  LOGIN: 'Login',
  REGISTER: 'Register',
  PHONE: 'Phone',
  LOCATION: 'Location',
  PRESS_PROFILE: 'PressProfile',
  PRESS_SERVICE: 'PressService',
  CONTINUE_SCREEN: 'ContinueScreen',
  IMAGE_SCREEN: 'ImageScreen',
  PAYMENT_SCREEN: 'PaymentScreen',
  CONFIRMATION_SCREEN: 'ConfirmationScreen',
  VIEW_APPOINTMENT: 'ViewAppointment',
  SELECT_PAYMENT_SCREEN: 'SelectPaymentScreen',
  FILTER_SCREEN: 'FilterScreen',
  BUSINESS_ONBOARDING: 'BusinessOnboarding',
  FULL_MAP_SCREEN: 'FullMapScreen',
  NOTIFICATIONS_SCREEN: 'NotificationsScreen',
  NAME_SCREEN: 'NameScreen',
  PERSONAL_SCREEN: 'PersonalScreen',
};
